name: apalog_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyterlab
  - r-BiocManager
  - r-data.table
  - r-IRkernel
  - r-nnet
  - r-plyr
  - r-utils
  - bioconductor-EnhancedVolcano
